FROM golang:alpine
MAINTAINER "Tim Fall <tim@hashicorp.com>"

RUN apk add --update git bash
RUN go get github.com/mitchellh/gox
RUN go get github.com/tools/godep
RUN go get github.com/hashicorp/nomad

WORKDIR $GOPATH/src/github.com/hashicorp/nomad

RUN godep restore .../.

RUN /bin/bash scripts/build.sh

WORKDIR $GOPATH
ENTRYPOINT ["bin/nomad"]
