FROM golang:alpine
MAINTAINER "Tim Fall <tim@hashicorp.com>"

RUN apk add --update git bash
RUN go get github.com/tools/godep
RUN go get github.com/hashicorp/terraform

WORKDIR $GOPATH/src/github.com/hashicorp/terraform

RUN godep restore -v .../.

ENV TF_DEV=true

RUN /bin/bash scripts/build.sh

WORKDIR $GOPATH
ENTRYPOINT ["bin/terraform"]
