FROM golang:alpine
MAINTAINER "Matt Hooker <mhooker@hashicorp.com>"

ENV PACKER_DEV=1

RUN apk add --update git bash
RUN go get github.com/mitchellh/gox
RUN go get github.com/mitchellh/packer

WORKDIR $GOPATH/src/github.com/mitchellh/packer

RUN /bin/bash scripts/build.sh

WORKDIR $GOPATH
ENTRYPOINT ["bin/packer"]
