FROM golang:alpine
LABEL maintainer="The Packer Team <packer@hashicorp.com>"

ENV PACKER_DEV=1

RUN apk add --no-cache git bash openssl ca-certificates
RUN git clone https://github.com/mitchellh/gox $GOPATH/src/github.com/mitchellh/gox
RUN git clone https://github.com/hashicorp/packer $GOPATH/src/github.com/hashicorp/packer

WORKDIR $GOPATH/src/github.com/hashicorp/packer

RUN /bin/bash scripts/build.sh

WORKDIR $GOPATH
ENTRYPOINT ["bin/packer"]
