FROM golang:alpine
MAINTAINER "Tim Fall <tim@hashicorp.com>"

RUN apk add --update git bash
RUN go get github.com/mitchellh/gox
RUN go get github.com/tools/godep
RUN go get github.com/hashicorp/vault

WORKDIR $GOPATH/src/github.com/hashicorp/vault

RUN godep restore -v .../.

RUN /bin/bash scripts/build.sh

WORKDIR $GOPATH
ENTRYPOINT ["bin/vault"]
